export enum Technology {
	React = "React",
	TypeScript = "TypeScript",
	Vite = "Vite",
	NextJS = "Next.js",
	TailwindCSS = "TailwindCSS",
	PostgreSQL = "PostgreSQL",
	SQLite = "SQLite",
	SQL = "SQL",
	Python = "Python",
	Rust = "Rust",
	CPP = "C++",
	Flask = "Flask",
	JavaScript = "JavaScript",
	NodeJS = "Node.js",
	Git = "Git",
	GitHub = "GitHub",
	Vercel = "Vercel",
	Figma = "Figma",
	Java = "Java",
	SpringBoot = "Spring Boot",
	AWS = "AWS",
	GCP = "GCP",
	Nginx = "Nginx"
}
